//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_passengers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_route_id: Uuid,
    pub adult_men: i16,
    pub adult_women: i16,
    pub child_men: i16,
    pub child_women: i16,
    pub handicap_adult_men: i16,
    pub handicap_adult_women: i16,
    pub handicap_child_men: i16,
    pub handicap_child_women: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_routes::Entity",
        from = "Column::UserRouteId",
        to = "super::user_routes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserRoutes,
}

impl Related<super::user_routes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoutes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
